# Generated by Django 5.0.2 on 2024-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=55)),
                ('cv', models.FileField(upload_to='media/app')),
                ('current_location', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=200)),
            ],
        ),
    ]
