# Generated by Django 5.0.2 on 2024-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
