# Generated by Django 5.0.2 on 2024-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_password_customuser_password1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
