# Generated by Django 5.0.2 on 2024-02-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('job_location', models.CharField(max_length=255, null=True)),
                ('job_description', models.TextField(null=True)),
                ('skills_required', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=66, null=True)),
                ('employee_role', models.CharField(max_length=70, null=True)),
                ('experience_required', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
