# Generated by Django 5.0.2 on 2024-02-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobposting_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='employee_role',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='city',
            new_name='posting_date',
        ),
    ]
