# Generated by Django 5.0.2 on 2024-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_employee_role_jobposting_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='email',
            field=models.EmailField(default='something@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='mobile_no',
            field=models.CharField(default='Mobile Number', max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='name',
            field=models.CharField(default=' Name', max_length=200),
        ),
    ]
