# Generated by Django 5.0.2 on 2024-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobposting_company_name_jobposting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5RhqcwxGDJustOfPZ5ybmAWzysfuMvTAYoUyVx63gKBwNRIeMm9kDwlS5NEN6I6vrnac&usqp=CAU', null=True, upload_to=''),
        ),
    ]
