# Generated by Django 5.0.2 on 2024-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobposting_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_logo',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5RhqcwxGDJustOfPZ5ybmAWzysfuMvTAYoUyVx63gKBwNRIeMm9kDwlS5NEN6I6vrnac&usqp=CAU', null=True, upload_to='media/app'),
        ),
    ]
