# Generated by Django 5.0.2 on 2024-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_jobposting_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, null=True)),
                ('mobile_no', models.CharField(max_length=255, null=True)),
                ('about_me', models.TextField(null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('joining_date', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=66, null=True)),
                ('priveus_job', models.CharField(max_length=70, null=True)),
                ('projects', models.CharField(max_length=200, null=True)),
                ('project_desc', models.CharField(max_length=200, null=True)),
                ('interests', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='company_logo',
        ),
    ]
