# Generated by Django 5.0.2 on 2024-02-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_edituser_remove_jobposting_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='edituser',
            name='gender',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
