# Generated by Django 5.0.2 on 2024-02-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_edituser_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='edituser',
            old_name='project_desc',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='edituser',
            name='type',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='edituser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('type', models.IntegerField(default=1, max_length=1)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
