# Generated by Django 5.0.2 on 2024-02-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_project_desc_edituser_specialization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.AlterField(
            model_name='edituser',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
