# Generated by Django 5.0.2 on 2024-02-29 01:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_employer_alter_edituser_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditUser',
            new_name='UserDetails',
        ),
    ]
