# Generated by Django 5.0.1 on 2024-02-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='projects',
        ),
    ]
