# Generated by Django 5.0.2 on 2024-02-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_userdetails_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='joining_date',
        ),
    ]
