# Generated by Django 5.0.2 on 2024-03-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_userdetails_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_img',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5RhqcwxGDJustOfPZ5ybmAWzysfuMvTAYoUyVx63gKBwNRIeMm9kDwlS5NEN6I6vrnac&usqp=CAU', null=True, upload_to='UserDetails'),
        ),
    ]
