# Generated by Django 5.0.2 on 2024-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userdetails_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdetails',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='CompanyLogos'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='UserDetails'),
        ),
    ]
